### ISSUE TITLE
Update to zarafa 7.2.x

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#107]
- 7.2.1 most probably
- should be provided only for  4.1 (not 3.x, and anymore for not 4.0)

Whishlist:
- have new description ready #100 
- create separate app for webapp #106

**Comment by fbartels** [comment]
The package libtcmalloc-minimal4 has to be included in the zarafa5ucs repo (currently only in unmaintained) for the 7.2 upgrade to complete.

**Comment by ngulden** [comment]
The update of Zarafa 7.2.1 will only be provided for UCS 4.1 at first place.

**Comment by edamrose** [comment]
Fixed with App version 7.2.1-51838
