### ISSUE TITLE
Display of Zarafa sendas occurs step-by-step

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#12]
Migrated from: https://jira.zarafa.com/browse/ZUCS-12

Dates
Created:	14/Jun/12 3:25 PM
Updated:	11/Sep/13 3:34 PM

Description
Opening a tab, there are no hits at first and first edit could start: At first, changing the tab and returning to the orginal one, the entries appear.
With 700 users and e.g. 5-6 send-as users UMC needs some time until the sendas users are listed on the Zarafa tab. Switching to the tab, there are at first sendas users + one empty box. Step by step the entries are displayed in the boxes. More sendas users take more time until the administrator can start with editing.
Background: At one customer the uid has been used instead of uidNumber. That saves the "translation", but may still be problematic.

**Comment by edamrose** [comment]
The current UMC will load the complete user object before displaying it, which would resolve part of this issue regarding step-by-step loading. Performance issues while opening a user with many sendAs references is worked on at Issue #71, so i am closing this one
