### ISSUE TITLE
With UCR set configuration variables are not activated

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#13]
Migrated from: https://jira.zarafa.com/browse/ZUCS-13

Dates
Created:	14/Jun/12 3:32 PM
Updated:	11/Sep/13 3:33 PM

Description
Setting Zarafa configuration variables with UCR are not activated after setting them. It has to be checked, if the problem is only valid with Zarafa4UCS or if it is a UCS bug. If it is a UCS bug, it has to be filed at http://forge.univention.de/

**Comment by edamrose** [comment]
Closing this, it WORKSFORME. Please open another issue if this happens again
