### ISSUE TITLE
ucr commit on a single Zarafa configuration file does not work

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#14]
Migrated from: https://jira.zarafa.com/browse/ZUCS-14

Dates
Created:	14/Jun/12 3:34 PM
Updated:	11/Sep/13 3:33 PM

Description
Files with the UCR variable set are not rewritten upon executing the command ucr commit /etc/zarafa/<configuration file>.

**Comment by edamrose** [comment]
The reason is that the cfg files are not UCR templates. Currently the UCR module zarafa-cfg parses existing cfg files and replaces single lines with values stored under UCR zarafa/cfg/*

**Comment by edamrose** [comment]
Nothing more to do here
