### ISSUE TITLE
Configuration support for Zarafa Multiserver environments

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#20]
Migrated from: https://jira.zarafa.com/browse/ZUCS-20

Dates
Created:	14/Jun/12 4:00 PM
Updated:	22/Sep/14 3:58 PM

Description
Zarafa4UCS should use the possibilities of UCS to simplify the configuration of Zarafa multi server environments.

depended on by ZUCS-21 Outsourced Zarafa webaccess for access from the Internet #21 + ZUCS-29 Integration of Zarafa Archiver #29 

Nico Gulden added a comment - 01/Oct/12 10:19 AM
Has been tried based on Zarafa4UCS 7.0 and Zarafa 7.1 on UCS 3.0-2: http://forum.univention.de/viewtopic.php?f=28&t=1990&p=6963

Nico Gulden added a comment - 22/Sep/14 3:58 PM
Requested by a partner are the following properties for this integration:
A host (UCS system) should receive the property "zarafa-server" and the corresponding attributes will be set (filepath, port, sslport, containspublic, …)
At a user object, the administrator should define the zarafaUserServer and the zarafaArchiverServer (see ZUCS-2).
The partner emphasizes that ldap_server_address_attribute (default: ipHostNumber) must not contain an IP address, but needs a FQDN. Otherwise, kerberos will not work in the multiserver environment.

**Comment by edamrose** [comment]
Multiserver support added by package zarafa4ucs-multiserver in App Center Version Zarafa 7.1.14-51822, see also https://wiki.z-hub.io/display/Z4U/Setting+up+Zarafa+Multiserver
