### ISSUE TITLE
Document time configuration for UCS server password change

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#37]
Migrated from: https://jira.zarafa.com/browse/ZUCS-37

Dates
Created:	02/Aug/12 11:01 AM
Updated:	02/Aug/12 11:02 AM

Description
The server password change in UCS takes places on a regular basis. The documentation should describe how to configure a certain date/time for the server password change or link to the appropriate UCS documentation.

depends on Bug - ZUCS-36 UCS server password change requires a restart of zarafa-server instead of a reload

**Comment by edamrose** [comment]
zarafau4ucs includes a server password script at server_password_change.d/70zarafa, which takes care of restarting the zarafa-server automatically in the event of a server password change. Is there anything left to do for this issue? What should be documented where?

**Comment by fbartels** [comment]
Imho this can be regarded as solved.
