### ISSUE TITLE
Show UCS mailinglist objects in Zarafa GAB

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#46]
Migrated from: https://jira.zarafa.com/browse/ZUCS-46

Dates
Created:	01/Nov/12 5:06 PM
Updated:	01/Nov/12 5:08 PM

Description
UCS admins are able to create UCS mailinglist objects that are used by postfix for mail distribution to several internal and external mail addresses. Currently the primary mail address of the mailinglist does not show up in Zarafa GAB.
By adding appropriate LDAP attributes/objectclasses UCS mailinglists could be listed as Zarafa contact in Zarafa GAB.
Current workaround:
create a bunch of UCS extended attributes to add the required attributes to UCS mailinglist objects.

**Comment by edamrose** [comment]
request expired
