### ISSUE TITLE
E-Mail address is assigned to multiple user accounts

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#48]
Migrated from: https://jira.zarafa.com/browse/ZUCS-48

Dates
Created:	29/Nov/12 11:00 AM
Updated:	11/Sep/13 3:34 PM

Description
A user has the following user setup:
user A:
primary email address: a@domain.qa
alternative email address: b@domain.qa
Mails to b@domain.qa a delivered to user A. Furthermore, the sender receives a notification that the email could not be delivered, because the user does not exist:
—
<b@domain.qa>: host 127.0.0.1[127.0.0.1] said: 503 5.1.1 User does not exist (in reply to RCPT TO command)
—
On UCS everything looks ok. At a short glance it could not be determined how Zarafa deals with alternative email addresses and if Zarafa does support them. In the default mail stack on UCS both users would receive the email.

**Comment by edamrose** [comment]
This could not be reproduced with 7.1.12 -> WORKSFORME
