### ISSUE TITLE
Account expiration not yielded by Zarafa

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#49]
Migrated from: https://jira.zarafa.com/browse/ZUCS-49

Dates
Created:	21/Jan/13 4:17 PM
Updated:	10/Jun/14 4:12 PM

Description
A customer has user accounts with an account expiration date set. After passing the expiration date the user is still allowed to login via WebAccess (and maybe WebApp). But the user should not be able to login. The expiration works for default domain user authentication from a client, he cannot login.
Deactivated accounts work as expected, the user cannot login to Zarafa.

Nico Gulden added a comment - 19/Mar/13 4:01 PM
Mentioned by a user in the Univention forum: http://forum.univention.de/viewtopic.php?f=48&t=2469&p=8450

Soenke Schwardt-Krummrich added a comment - 10/Jun/14 4:12 PM
I think the customer at forum.univention.de aims at the password expiration date (not the account expiration date!). The password expiration date should force the user to change its password not later than the specified date.
When reaching the account expiration date, the whole account should be disabled. Currently this doesn't work correctly in UCS (and therefore Zarafa) and will be fixed by an erratum for UCS 3.2-2.

**Comment by edamrose** [comment]
This will be fixed in UCS:
https://forge.univention.org/bugzilla/show_bug.cgi?id=35088
https://forge.univention.org/bugzilla/show_bug.cgi?id=36215
