### ISSUE TITLE
Change displayname from LDAP attribute cn to displayName

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#50]
Migrated from: https://jira.zarafa.com/browse/ZUCS-50

Dates
Created:	22/Jan/13 11:26 AM
Updated:	22/Jan/13 11:26 AM

Description
A customer requests to change the default LDAP attribute for displaying the user name in Zarafa from the Zarafa default "cn" to "displayName". The topic needs to be discussed.
http://forum.univention.de/viewtopic.php?f=28&t=2210
The setting can be changed with the following commands:
ucr set zarafa/cfg/ldap/ldap_fullname_attribute=displayName
zarafa-admin --sync

**Comment by edamrose** [comment]
This zarafa default settings will currently not be changed.
