### ISSUE TITLE
Change Zarafa default user flag to true

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#51]
Migrated from: https://jira.zarafa.com/browse/ZUCS-51

Dates
Created:	29/Jan/13 3:46 PM
Updated:	29/Jan/13 3:46 PM

Description
Zarafa4UCS controls whether a user can access Zarafa webaccess or not with the LDAP attribute zarafaRole. After installation of Zarafa this attribute defaults to None.
The default should be changed to "Zarafa User" so that every existing and new user is allowed to use Zarafa. This excludes system users or other accounts not being real user accounts or not having a primary email address. This behaviour also benefits environments where UCS is connected to Microsoft Active Directory through UCS AD Connector.
If a user should not use Zarafa, it has to be configured explicitely.

**Comment by edamrose** [comment]
AD Connector Mode: With App Center Version 7.1.12 AD users who have an e-mail address are converted to zarafa users on sync to ucs

**Comment by edamrose** [comment]
From Univention and Zarafa point of view nothing else has to be done here.
