### ISSUE TITLE
dd zarafa-backup package as recommended package to zarafa4ucs meta-package

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#52]
Migrated from: https://jira.zarafa.com/browse/ZUCS-52

Dates
Created:	06/Feb/13 4:14 PM
Updated:	06/Feb/13 4:14 PM

Description
A new installation of Zarafa on UCS does not install the package zarafa-backup. The package is available in the App Center repository and can be installed manually after the Zarafa installation.
It should be evaluated if the automatic installation of zarafa-backup together with Zarafa makes sense and meets the users' needs in contrast to a manual installation afterwards.

**Comment by fbartels** [comment]
Just to clarify. The zarafa-backup package is included in the normal repository and just has to be installed eg ```univention-install zarafa-backup```

**Comment by edamrose** [comment]
Recommend added in App Center Version Zarafa 7.1.14-51822
