### ISSUE TITLE
Revise the usability of the Zarafa tab at the user object

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#54]
Migrated from: https://jira.zarafa.com/browse/ZUCS-54

Dates
Created:	18/Mar/13 12:27 PM
Updated:	18/Mar/13 12:32 PM

Description
The Zarafa Tab in the UCS management system contains the Zarafa settings for the user object. The field order should be revised and usability should be taken into account.

**Comment by edamrose** [comment]
Request is to unspecific. Please open a new issue if there is a problem
