### ISSUE TITLE
Installation via App Center leaves two join scripts not executed

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#55]
Migrated from: https://jira.zarafa.com/browse/ZUCS-55

Dates
Created:	07/Jun/13 2:00 PM
Updated:	11/Sep/13 3:30 PM

Description
The installation of Zarafa via Univention App Center leaves two join scripts not executed in the join overview. They can be run manually. The join scripts' purpose is to activate and deactivate the "safe_mode" upon a (re-)join to prevent orphaned mailboxes.
It should be checked, whether the join scripts are still needed. If yes, it should be taken care that they are working properly and meet their purpose.

**Comment by edamrose** [comment]
See also Issue #70

**Comment by edamrose** [comment]
Will be removed in a future update

**Comment by edamrose** [comment]
The joinscripts will be marked as executed by default with App Center Version Zarafa 7.1.14-51822. This should avoid confusion, while ensuring safe mode will be activated during a rejoin
