### ISSUE TITLE
Run Zarafa as a dedicated system user and enhance security

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#57]
Migrated from: https://jira.zarafa.com/browse/ZUCS-57

Dates
Created:	10/Jul/13 3:48 PM
Updated:	10/Jul/13 3:48 PM

Description
In the Zarafa Server Config file a user for the zarafa-server process can be configured. This enhances security as errors in Zarafa cannot be used to gain additional system privileges.
Suggestion: Change the default process user for Zarafa to a dedicated system user.

**Comment by edamrose** [comment]
This is planned to be integrated in a future zarafa version. We will not solve this separately in the integration package
