### ISSUE TITLE
SSLv2 should be enabled by default

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#58]
Migrated from: https://jira.zarafa.com/browse/ZUCS-58

Dates
Created:	10/Jul/13 3:50 PM
Updated:	11/Sep/13 3:33 PM

Description
By default SSLv2 is disabled. This however prevents the usage of Microsoft Outlook and Zarafa. It would therefore be good, if the integration package would enable the usage of SSLv2 by default.

**Comment by edamrose** [comment]
How would the correct configuration look like? The current SSL settings with App Center Version 7.1.12 are:
server_ssl_enabled = yes
server_ssl_port         = 237
server_ssl_protocols = !SSLv2
server_ssl_ciphers = ALL:!LOW:!SSLv2:!EXP:!aNULL
server_ssl_prefer_server_ciphers = no

**Comment by fbartels** [comment]
The original ticket description is not valid anymore and SSLv2 (acutally not even SSLv3) should be used anymore. SSLv3 is currently still needed as only clients >7.1.11 can use more secure ciphers.

As this ticket is about SSLv2 this should be closed.
