### ISSUE TITLE
Search filter problem with Outlook name check

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#61]
Migrated from: https://jira.zarafa.com/browse/ZUCS-61

Dates
Created:	24/Feb/14 9:25 PM
Updated:	25/Feb/14 6:13 AM
Resolved:	24/Feb/14 9:25 PM

Description
A partner reported that the name check in Outlook together with Zarafa on UCS does not yield the expected user, while typing the first part of a name in the To field and a click on "name check". Reason may be the search filter.
"(&(|(&(zarafaAccount=1)(|(objectClass=zarafa-user)(objectClass=zarafa-contact)))(&(zarafaAccount=1)(objectClass=zarafa-contact))(|(&(objectClass=posixGroup)(&(zarafaAccount=1)(objectClass=zarafa-group)))(objectClass=zarafa-dynamicgroup))(|(&(objectClass=zarafa-addresslist))))(|(uid=fel*)(description=fel*)(mailPrimaryAddress=fel*)(mailAlternativeAddress=fel*)(description=fel*)(ou=fel*)(cn=fel*)(cn=fel*)))"
It is always searched for "fel*", but "*fel*" is needed.
Proposed solution:
Change ldap_addresslist_name_attribute = sn
Change ldap_groupmembers_attribute = uniqueMember
Change ldap_groupmembers_attribute_type = dn

**Comment by edamrose** [comment]
We are currently not sure about possible side effects. Closing until further affected users are reported
