### ISSUE TITLE
Mistake in zarafa4ucs.schema

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#69]
Migrated from: https://jira.zarafa.com/browse/ZUCS-69

Dates
Created:	19/Feb/15 1:27 PM
Updated:	19/Feb/15 1:27 PM
Resolved:	19/Feb/15 1:27 PM

Description
In the zaraf4ucs ldap scheme file is a little mistake according the objectClass zarafa-company.
Original scheme:
objectclass ( 1.3.6.1.4.1.26278.1.3.0.0
NAME 'zarafa-company'
DESC 'ZARAFA: a company of Zarafa'
SUP top AUXILIARY
MUST ( ou )
Zarafa4UCS scheme:
objectclass ( 1.3.6.1.4.1.26278.1.3.0.0
NAME 'zarafa-company'
DESC 'ZARAFA: a company of Zarafa'
SUP top AUXILIARY
MUST ( cn )
The MUST should be ou not cn. As an organizational unit does not have the cn attribute as a standard, this should be changed.

**Comment by edamrose** [comment]
Fixed in App Center Version 7.1.12 with package zarafa4ucs 7.1.3000-8
