### ISSUE TITLE
Add user template for creating a Zarafa contact

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#7]
Migrated from: https://jira.zarafa.com/browse/ZUCS-7

Dates
Created:	20/Mar/12 5:00 PM
Updated:	11/Sep/13 3:04 PM

Description
For adding a new user object as Zarafa contact, Zarafa4UCS should provide a user template taking care of all the necessary default settings. The user object must have the following default settings provided by the template:
- Tab Zarafa: Zarafa role == Zarafa Contact
- Tab Option: "Mail Account" and "Personal information"

Nico Gulden added a comment - 11/Jun/12 4:13 PM
This feature is partly implemented except of the point with "Mail Account" and "Personal information" on the the tab option. The current implementation (version 7.0) provides the user template that sets Zarafa role to user and takes care of the email address.

**Comment by edamrose** [comment]
zarafa4ucs Versions prior App Center Version 7.1.12 already had a Zarafa-Contact template. With 7.1.12 we have seperate UMC / UDM modules for handling contacts and nonactive users. Closing this as WORKSFORME
