### ISSUE TITLE
Save mode join scripts not executed

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#70]
Migrated from: https://jira.zarafa.com/browse/ZUCS-70

Dates
Created:	27/Feb/15 2:08 PM
Updated:	27/Feb/15 2:10 PM

Description
The two join scripts for Zarafa safe-mode are not executed automatically, if Zarafa is for example installed on a UCS DC backup.
Technically it is not a problem, but it is irritating for the user since he receives a notification about not executed join scripts.
Reported with Univention Ticket #2015022521000374

**Comment by edamrose** [comment]
See also Issue 55

**Comment by fbartels** [comment]
Closing because it is a duplicate of #55
