### ISSUE TITLE
Zarafa search requires deletion and rebuild of index to work

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#72]
Migrated from: https://jira.zarafa.com/browse/ZUCS-72

Dates
Created:	16/Mar/15 9:46 AM
Updated:	07/Apr/15 12:13 PM

Description
We received multiple reports [1] that the search function in webapp, webaccess and outlook stops working after an unspecified time.
Workaround:
Stop zarafa-search service
delete /var/lib/zarafa
Start zarafa-search service
There may be support cases associated with this, see the forum thread [1]
[1] http://forum.univention.de/viewtopic.php?f=67&t=3617

**Comment by edamrose** [comment]
This is a zarafa-core issue and not UCS specific
