### ISSUE TITLE
Add dependency to univention-sasl to zarafa4ucs

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#73]
Migrated from: https://jira.zarafa.com/browse/ZUCS-73

Dates
Created:	07/Apr/15 12:12 PM
Updated:	07/Apr/15 12:12 PM

Description
External connections from E-Mailclients to the server are not
possible out-of-the-box with a fresh app installation, the package
univention-sasl is missing. A dependency should be added to the
metapackage zarafa4ucs.

**Comment by edamrose** [comment]
Fixed in App Center Version 7.1.12 with package zarafa4ucs 7.1.3000-8
