### ISSUE TITLE
Segfault Zarafa-Server after update

### ISSUE THREAD

**Issue by ngulden** [zarafa4ucs/zarafa4ucs#75]
{noformat}
Thu Apr 30 10:05:40 2015: [fatal  ] 0x4ce711 /usr/bin/zarafa-server(_Z7sigsegvi+0x81) [0x4ce711]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x7f54149bc0a0 /lib/x86_64-linux-gnu/libpthread.so.0(+0xf0a0) [0x7f54149bc0a0]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x573f0c /usr/bin/zarafa-server(_Z26zarafa_new_soap_connection15CONNECTION_TYPEP4soap+0x4c) [0x573f0c]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x4db5b6 /usr/bin/zarafa-server(_ZN17ECDispatcherEPoll8MainLoopEv+0x276) [0x4db5b6]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x4d37e4 /usr/bin/zarafa-server(_Z14running_serverPcPKciPS_+0x2684) [0x4d37e4]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x4cd6f9 /usr/bin/zarafa-server(main+0x279) [0x4cd6f9]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x7f5412490ead /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f5412490ead]
Thu Apr 30 10:05:41 2015: [fatal  ] 0x4ce5a9 /usr/bin/zarafa-server() [0x4ce5a9]
{noformat}

no coredump written

Reported at https://jira.zarafa.com/browse/ZUCS-74 and moved to GitHub.

**Comment by edamrose** [comment]
zarafa core bug, handled via zarafa support
