### ISSUE TITLE
Reimplement the possibility to easily change an active user to a shared mailbox

### ISSUE THREAD

**Issue by fbartels** [zarafa4ucs/zarafa4ucs#88]
Zarafa4UCS prior to the 7.1.12 had the easy possibility to change to type of a user from active to inactive. Since these types are now managed separately and user cannot be switched easily.

Maybe include a script to move a user from one management module to the other?

**Comment by edamrose** [comment]
With App Center Version Zarafa 7.1.14-51822 UCS users can become non-active users again
