### ISSUE TITLE
Allow to move non-active and contact objects via UDM

### ISSUE THREAD

**Issue by jayme-github** [zarafa4ucs/zarafa4ucs#90]
It's now allowed to move non-active and contact objects via UDM.
If there is no konkrete reason to prohibit that, it should be allowed:

```patch
- operations = ['add', 'edit', 'remove', 'search']
+ operations = ['add', 'edit', 'remove', 'search', 'move']
```

**Comment by edamrose** [comment]
Fixed in App Center Version Zarafa 7.1.14-51822
